<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>preview</LangVersion>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>
	
	<PropertyGroup>

		<AnalysisMode>all</AnalysisMode>
		<AnalysisLevel>latest</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<WarningsAsErrors>true</WarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp"   />
	</ItemGroup>
</Project>