<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AnalysisMode>all</AnalysisMode>
		<AnalysisLevel>latest</AnalysisLevel>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\VerenaVision.Common\VerenaVision.Common.csproj" />
	  <ProjectReference Include="..\VerenaVision.SharedKernel\VerenaVision.SharedKernel.csproj" />
	</ItemGroup>

</Project>
